-- logic_ic classify 规则 · 23 条 rule_id · schema v1.4.30
-- 生成: python seed/gen_classify_insert_sql.py
INSERT INTO dim.dim_l3_classify_rule
(rule_id, clause_group_id, clause_ord, schema_version, data_source, rule_kind, l3_id, l3_cn, phase, rule_priority, enabled, confidence_weight, classify_source_hint, field_code, match_value, match_values, match_map, note)
VALUES
('logic_ic_dk_gate_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220101', '基本逻辑门', 2, 10, 1, 1.0, 'digikey_category', 'category_eq', '门和反相器', NULL, NULL, 'basic gate'),
('logic_ic_dk_config_gate_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220101', '基本逻辑门', 2, 10, 1, 1.0, 'digikey_category', 'category_eq', '门和反相器 - 多功能，可配置', NULL, NULL, 'configurable gate'),
('logic_ic_dk_comparator_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220104', '数字比较器', 2, 10, 1, 1.0, 'digikey_category', 'category_eq', '比较器', NULL, NULL, 'comparator leaf'),
('logic_ic_dk_parity_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220103', '编码器/解码器', 2, 10, 1, 1.0, 'digikey_category', 'category_eq', '奇偶校验发生器和校验器', NULL, NULL, 'parity gen/check'),
('logic_ic_dk_flip_flop_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220201', '触发器/锁存器', 2, 10, 1, 1.0, 'digikey_category', 'category_eq', '触发器', NULL, NULL, 'flip-flop leaf'),
('logic_ic_dk_shift_register_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220203', '移位寄存器', 2, 10, 1, 1.0, 'digikey_category', 'category_eq', '移位寄存器', NULL, NULL, 'shift register leaf'),
('logic_ic_dk_bus_switch_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220304', '总线开关', 3, 8, 1, 1.0, 'digikey_category', 'category_eq', '信号开关，多路复用器，解码器', NULL, NULL, 'mux leaf · bus switch'),
('logic_ic_dk_bus_switch_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220304', '总线开关', 3, 8, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '总线开关|交点开关', NULL, NULL, 'mux leaf · bus switch'),
('logic_ic_dk_decoder_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220103', '编码器/解码器', 3, 9, 1, 1.0, 'digikey_category', 'category_eq', '信号开关，多路复用器，解码器', NULL, NULL, 'mux leaf · decoder/demux'),
('logic_ic_dk_decoder_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220103', '编码器/解码器', 3, 9, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '解码器|多路分解|Demultiplex', NULL, NULL, 'mux leaf · decoder/demux'),
('logic_ic_dk_mux_encoder_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220103', '编码器/解码器', 3, 8, 1, 1.0, 'digikey_category', 'category_eq', '信号开关，多路复用器，解码器', NULL, NULL, 'mux leaf · priority encoder'),
('logic_ic_dk_mux_encoder_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220103', '编码器/解码器', 3, 8, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '优先顺序编码器|Priority Encoder', NULL, NULL, 'mux leaf · priority encoder'),
('logic_ic_dk_mux_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220102', '多路复用器/解复用器', 3, 10, 1, 1.0, 'digikey_category', 'category_eq', '信号开关，多路复用器，解码器', NULL, NULL, 'mux leaf · multiplexer'),
('logic_ic_dk_mux_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220102', '多路复用器/解复用器', 3, 10, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '多路复用|数据选择器|Multiplex', NULL, NULL, 'mux leaf · multiplexer'),
('logic_ic_dk_mux_fb_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220102', '多路复用器/解复用器', 1, 99, 1, 1.0, 'digikey_category', 'category_eq', '信号开关，多路复用器，解码器', NULL, NULL, 'mux leaf fallback'),
('logic_ic_dk_special_counter_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220204', '计数器/分频器', 3, 8, 1, 1.0, 'digikey_category', 'category_eq', '专用逻辑器件', NULL, NULL, 'specialty counter'),
('logic_ic_dk_special_counter_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220204', '计数器/分频器', 3, 8, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '计数器|分频|Counter', NULL, NULL, 'specialty counter'),
('logic_ic_dk_special_adder_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220105', '算术逻辑单元/加法器', 3, 9, 1, 1.0, 'digikey_category', 'category_eq', '专用逻辑器件', NULL, NULL, 'specialty adder/alu'),
('logic_ic_dk_special_adder_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220105', '算术逻辑单元/加法器', 3, 9, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '加法器|全加|算术逻辑单元|ALU|Adder', NULL, NULL, 'specialty adder/alu'),
('logic_ic_dk_special_regbuf_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220301', '缓冲器/线驱动器', 3, 10, 1, 1.0, 'digikey_category', 'category_eq', '专用逻辑器件', NULL, NULL, 'specialty register buffer → buffer_driver'),
('logic_ic_dk_special_regbuf_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220301', '缓冲器/线驱动器', 3, 10, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '寄存缓冲器|Register Buffer|DDR', NULL, NULL, 'specialty register buffer → buffer_driver'),
('logic_ic_dk_special_flipflop_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220201', '触发器/锁存器', 3, 11, 1, 1.0, 'digikey_category', 'category_eq', '专用逻辑器件', NULL, NULL, 'specialty flip-flop/latch'),
('logic_ic_dk_special_flipflop_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220201', '触发器/锁存器', 3, 11, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '触发器|锁存|Flip[ -]?Flop|Latch', NULL, NULL, 'specialty flip-flop/latch'),
('logic_ic_dk_special_register_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220202', '寄存器', 3, 12, 1, 1.0, 'digikey_category', 'category_eq', '专用逻辑器件', NULL, NULL, 'specialty register'),
('logic_ic_dk_special_register_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220202', '寄存器', 3, 12, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '寄存器|Register', NULL, NULL, 'specialty register'),
('logic_ic_dk_special_comparator_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220104', '数字比较器', 3, 13, 1, 1.0, 'digikey_category', 'category_eq', '专用逻辑器件', NULL, NULL, 'specialty comparator'),
('logic_ic_dk_special_comparator_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220104', '数字比较器', 3, 13, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '比较器|Comparator', NULL, NULL, 'specialty comparator'),
('logic_ic_dk_special_transceiver_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220302', '总线收发器', 3, 14, 1, 1.0, 'digikey_category', 'category_eq', '专用逻辑器件', NULL, NULL, 'specialty transceiver'),
('logic_ic_dk_special_transceiver_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220302', '总线收发器', 3, 14, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '收发器|Transceiver', NULL, NULL, 'specialty transceiver'),
('logic_ic_dk_special_buffer_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220301', '缓冲器/线驱动器', 3, 15, 1, 1.0, 'digikey_category', 'category_eq', '专用逻辑器件', NULL, NULL, 'specialty buffer/driver'),
('logic_ic_dk_special_buffer_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220301', '缓冲器/线驱动器', 3, 15, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '缓冲器|Buffer|驱动器|Driver|接收器', NULL, NULL, 'specialty buffer/driver'),
('logic_ic_dk_special_fb_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220301', '缓冲器/线驱动器', 1, 99, 1, 1.0, 'digikey_category', 'category_eq', '专用逻辑器件', NULL, NULL, 'specialty fallback'),
('logic_ic_dk_buffer_transceiver_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220302', '总线收发器', 3, 10, 1, 1.0, 'digikey_category', 'category_eq', '缓冲器，驱动器，接收器，收发器', NULL, NULL, 'buffer leaf · transceiver'),
('logic_ic_dk_buffer_transceiver_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220302', '总线收发器', 3, 10, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '收发器|Transceiver', NULL, NULL, 'buffer leaf · transceiver'),
('logic_ic_dk_buffer_driver_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220301', '缓冲器/线驱动器', 3, 11, 1, 1.0, 'digikey_category', 'category_eq', '缓冲器，驱动器，接收器，收发器', NULL, NULL, 'buffer leaf · buffer/line driver'),
('logic_ic_dk_buffer_driver_v1', '0', '1', 'v1.4.30', 'digikey', 'classify', '220301', '缓冲器/线驱动器', 3, 11, 1, 1.0, 'note_cn_regexp', 'note_cn_regexp', '缓冲器|Buffer|线路驱动|驱动器', NULL, NULL, 'buffer leaf · buffer/line driver'),
('logic_ic_dk_buffer_fb_v1', '0', '0', 'v1.4.30', 'digikey', 'classify', '220301', '缓冲器/线驱动器', 1, 99, 1, 1.0, 'digikey_category', 'category_eq', '缓冲器，驱动器，接收器，收发器', NULL, NULL, 'buffer leaf fallback · note 空');
