"""circuit_protection ICPDF classify 规则真源（gate 见 gate_config.py）。

决选：phase DESC → rule_priority ASC → l3_code ASC
"""
from __future__ import annotations

SCHEMA_VERSION = "v1.16.01"
DATA_SOURCE = "icpdf"

CLASSIFY_RULES: list[dict] = [
    # ── phase 3 · prajson2 电路保护类型（tag 路径）──
    {
        "rule_id": "circuit_protection_icpdf_prajson2_breaker_tm_v1",
        "l3_id": "160104",
        "l3_cn": "断路器",
        "phase": 3,
        "rule_priority": 5,
        "clauses": [("parjson2_match_map", None, None, {"电路保护类型": "THERMAL MAGNETIC"})],
        "note": "prajson2.电路保护类型 → 断路器",
        "classify_source_hint": "prajson2",
    },
    {
        "rule_id": "circuit_protection_icpdf_prajson2_breaker_tcb_v1",
        "l3_id": "160104",
        "l3_cn": "断路器",
        "phase": 3,
        "rule_priority": 5,
        "clauses": [("parjson2_match_map", None, None, {"电路保护类型": "THERMAL CIRCUIT BREAKER"})],
        "note": "prajson2.电路保护类型 → 断路器",
        "classify_source_hint": "prajson2",
    },
    {
        "rule_id": "circuit_protection_icpdf_prajson2_breaker_mcb_v1",
        "l3_id": "160104",
        "l3_cn": "断路器",
        "phase": 3,
        "rule_priority": 5,
        "clauses": [("parjson2_match_map", None, None, {"电路保护类型": "MAGNETIC CIRCUIT BREAKER"})],
        "note": "prajson2.电路保护类型 → 断路器",
        "classify_source_hint": "prajson2",
    },
    {
        "rule_id": "circuit_protection_icpdf_prajson2_breaker_elcb_v1",
        "l3_id": "160104",
        "l3_cn": "断路器",
        "phase": 3,
        "rule_priority": 5,
        "clauses": [
            ("parjson2_match_map", None, None, {"电路保护类型": "EQUIPMENT LEAKAGE CIRCUIT BREAKER"})
        ],
        "note": "prajson2.电路保护类型 → 断路器",
        "classify_source_hint": "prajson2",
    },
    {
        "rule_id": "circuit_protection_icpdf_prajson2_thermal_fuse_v1",
        "l3_id": "160103",
        "l3_cn": "热熔断体(温度保险丝)",
        "phase": 3,
        "rule_priority": 6,
        "clauses": [("parjson2_match_map", None, None, {"电路保护类型": "THERMAL FUSE"})],
        "note": "prajson2.电路保护类型 → 热熔断",
        "classify_source_hint": "prajson2",
    },
    {
        "rule_id": "circuit_protection_icpdf_prajson2_electric_fuse_v1",
        "l3_id": "160101",
        "l3_cn": "保险丝(熔断器)",
        "phase": 3,
        "rule_priority": 8,
        "clauses": [("parjson2_match_map", None, None, {"电路保护类型": "ELECTRIC FUSE"})],
        "note": "prajson2.电路保护类型 → 保险丝",
        "classify_source_hint": "prajson2",
    },
    {
        "rule_id": "circuit_protection_icpdf_prajson2_electric_fuse2_v1",
        "l3_id": "160101",
        "l3_cn": "保险丝(熔断器)",
        "phase": 3,
        "rule_priority": 8,
        "clauses": [("parjson2_match_map", None, None, {"电路保护类型": "Electric Fuse"})],
        "note": "prajson2.电路保护类型 → 保险丝（大小写变体）",
        "classify_source_hint": "prajson2",
    },
    {
        "rule_id": "circuit_protection_icpdf_prajson2_electric_fuse3_v1",
        "l3_id": "160101",
        "l3_cn": "保险丝(熔断器)",
        "phase": 3,
        "rule_priority": 8,
        "clauses": [("parjson2_match_map", None, None, {"电路保护类型": "FUSE, ELECTRICAL"})],
        "note": "prajson2.电路保护类型 → 保险丝",
        "classify_source_hint": "prajson2",
    },
    # ── phase 3 · ESD note 专规（先于 TVS 宽规则）──
    {
        "rule_id": "circuit_protection_icpdf_esd_note_v1",
        "l3_id": "160202",
        "l3_cn": "ESD抑制器件",
        "phase": 3,
        "rule_priority": 4,
        "clauses": [("note_cn_regexp", "(?i)ESD", None, None)],
        "note": "note_cn 含 ESD → esd_suppressor",
        "classify_source_hint": "note_cn_regexp",
    },
    {
        "rule_id": "circuit_protection_icpdf_pptc_note_v1",
        "l3_id": "160102",
        "l3_cn": "自恢复保险丝(PPTC)",
        "phase": 3,
        "rule_priority": 4,
        "clauses": [
            ("note_cn_regexp", "(?i)(PPTC|自恢复|PolySwitch|polyswitch)", None, None)
        ],
        "note": "note_cn PPTC/自恢复 → pptc_resettable_fuse（优先于 fuse 电熔丝）",
        "classify_source_hint": "note_cn_regexp",
    },
    {
        "rule_id": "circuit_protection_icpdf_pptc_note_en_v1",
        "l3_id": "160102",
        "l3_cn": "自恢复保险丝(PPTC)",
        "phase": 3,
        "rule_priority": 3,
        "clauses": [
            (
                "note_regexp",
                "(?i)(PPTC|PolySwitch|PTC Thermistor|Resettable Fuse|自恢复)",
                None,
                None,
            )
        ],
        "note": "note 英文字段 PPTC/PTC Thermistor → pptc（ICPDF note_cn 常空）",
        "classify_source_hint": "note_regexp",
    },
    {
        "rule_id": "circuit_protection_icpdf_pptc_partno_v1",
        "l3_id": "160102",
        "l3_cn": "自恢复保险丝(PPTC)",
        "phase": 3,
        "rule_priority": 3,
        "clauses": [
            ("category_eq", "热熔断路器/开关/保险丝", None, None),
            (
                "partno_regexp",
                "(?i)^(MF-R|RHEF|RUEF|RGEF|NANOSMD|MINISMD|microSMD)",
                None,
                None,
            ),
        ],
        "note": "热熔断宽桶 + partno 前缀 → pptc（避免误伤 MOV 等）",
        "classify_source_hint": "partno_regexp",
    },
    {
        "rule_id": "circuit_protection_icpdf_tco_note_v1",
        "l3_id": "160103",
        "l3_cn": "热熔断体(温度保险丝)",
        "phase": 3,
        "rule_priority": 4,
        "clauses": [
            (
                "note_regexp",
                "(?i)(Thermal Cutoff|TCO\\)|温度保险|热熔断体|Thermal Fuse)",
                None,
                None,
            )
        ],
        "note": "note 真 TCO/温度保险 → thermal_cutoff（phase3 优先于 category 宽桶）",
        "classify_source_hint": "note_regexp",
    },
    {
        "rule_id": "circuit_protection_icpdf_tco_partno_v1",
        "l3_id": "160103",
        "l3_cn": "热熔断体(温度保险丝)",
        "phase": 3,
        "rule_priority": 4,
        "clauses": [("partno_regexp", "(?i)^EYP", None, None)],
        "note": "partno EYP* → thermal_cutoff（松下 TCO 系列）",
        "classify_source_hint": "partno_regexp",
    },
    {
        "rule_id": "circuit_protection_icpdf_prajson2_pptc_type_v1",
        "l3_id": "160102",
        "l3_cn": "自恢复保险丝(PPTC)",
        "phase": 3,
        "rule_priority": 5,
        "clauses": [
            ("parjson2_match_map", None, None, {"电阻器类型": "PTC RESETTABLE FUSE"})
        ],
        "note": "prajson2.电阻器类型=PTC RESETTABLE FUSE → pptc",
        "classify_source_hint": "prajson2",
    },
    {
        "rule_id": "circuit_protection_icpdf_spd_module_note_v1",
        "l3_id": "160401",
        "l3_cn": "浪涌保护模块(SPD)",
        "phase": 3,
        "rule_priority": 4,
        "clauses": [
            ("note_cn_regexp", "(线路浪涌保护模块|浪涌保护模块)", None, None)
        ],
        "note": "note 线路/浪涌保护模块 → spd_module（不用宽泛 SPD 避免 TSPD 误判）",
        "classify_source_hint": "note_cn_regexp",
    },
    # ── phase 3 · 电信保护电路（c2=电信保护电路 · 主 TSPD / 子 GDT）──
    {
        "rule_id": "circuit_protection_icpdf_telecom_gdt_v1",
        "l3_id": "160302",
        "l3_cn": "气体放电管(GDT)",
        "phase": 3,
        "rule_priority": 3,
        "clauses": [
            ("category2_eq", "电信保护电路", None, None),
            ("note_cn_regexp", "(气体放电|等离子|GDT)", None, None),
        ],
        "note": "电信叶 · note GDT/气体放电 → gdt",
        "classify_source_hint": "note_cn_regexp",
    },
    {
        "rule_id": "circuit_protection_icpdf_telecom_tspd_note_v1",
        "l3_id": "160203",
        "l3_cn": "晶闸管浪涌保护器(TSPD)",
        "phase": 3,
        "rule_priority": 5,
        "clauses": [
            ("category2_eq", "电信保护电路", None, None),
            ("note_cn_regexp", "(TRISIL|SIDAC)", None, None),
        ],
        "note": "电信叶 · TRISIL/SIDACtor → tspd",
        "classify_source_hint": "note_cn_regexp",
    },
    {
        "rule_id": "circuit_protection_icpdf_telecom_sidac_cat_v1",
        "l3_id": "160203",
        "l3_cn": "晶闸管浪涌保护器(TSPD)",
        "phase": 3,
        "rule_priority": 6,
        "clauses": [
            ("category2_eq", "电信保护电路", None, None),
            ("category_eq", "SIDAC开关型晶闸管", None, None),
        ],
        "note": "电信叶 · SIDAC category → tspd",
    },
    {
        "rule_id": "circuit_protection_icpdf_telecom_thy_cat_v1",
        "l3_id": "160203",
        "l3_cn": "晶闸管浪涌保护器(TSPD)",
        "phase": 3,
        "rule_priority": 6,
        "clauses": [
            ("category2_eq", "电信保护电路", None, None),
            ("category_eq", "晶闸管", None, None),
        ],
        "note": "电信叶 · 晶闸管 category → tspd",
    },
    {
        "rule_id": "circuit_protection_icpdf_telecom_surge_cat_v1",
        "l3_id": "160203",
        "l3_cn": "晶闸管浪涌保护器(TSPD)",
        "phase": 3,
        "rule_priority": 6,
        "clauses": [
            ("category2_eq", "电信保护电路", None, None),
            ("category_eq", "电涌保护", None, None),
        ],
        "note": "电信叶 · 电涌保护 category → tspd",
    },
    {
        "rule_id": "circuit_protection_icpdf_telecom_prajson2_surge_v1",
        "l3_id": "160203",
        "l3_cn": "晶闸管浪涌保护器(TSPD)",
        "phase": 3,
        "rule_priority": 8,
        "clauses": [
            ("category2_eq", "电信保护电路", None, None),
            ("parjson2_match_map", None, None, {"电信集成电路类型": "SURGE PROTECTION CIRCUIT"}),
        ],
        "note": "电信叶 · prajson 电信集成电路类型=SURGE PROTECTION CIRCUIT → tspd",
        "classify_source_hint": "prajson2",
    },
    {
        "rule_id": "circuit_protection_icpdf_cpdev_telecom_c2_v1",
        "l3_id": "160203",
        "l3_cn": "晶闸管浪涌保护器(TSPD)",
        "phase": 3,
        "rule_priority": 9,
        "clauses": [
            ("category_eq", "电路保护器件", None, None),
            ("category2_eq", "电信保护电路", None, None),
        ],
        "note": "category=电路保护器件 且 c2=电信保护电路 → tspd",
    },
    {
        "rule_id": "circuit_protection_icpdf_breaker_c2_v1",
        "l3_id": "160104",
        "l3_cn": "断路器",
        "phase": 3,
        "rule_priority": 10,
        "clauses": [("category2_eq", "断路器", None, None)],
        "note": "overcurrent · circuit_breaker（phase3 全局决选）",
    },
    {
        "rule_id": "circuit_protection_icpdf_tspd_c2_v1",
        "l3_id": "160203",
        "l3_cn": "晶闸管浪涌保护器(TSPD)",
        "phase": 3,
        "rule_priority": 5,
        "clauses": [("category2_eq", "硅浪涌保护器", None, None)],
        "note": "semiconductor · tspd（phase3 优先于 transistor p3）",
    },
    {
        "rule_id": "circuit_protection_icpdf_thermal_cutoff_cat_c2_v1",
        "l3_id": "160103",
        "l3_cn": "热熔断体(温度保险丝)",
        "phase": 3,
        "rule_priority": 8,
        "clauses": [
            ("category_eq", "热熔断路器/开关/保险丝", None, None),
            ("category2_eq", "电熔丝", None, None),
        ],
        "note": "热熔断 + 电熔丝 c2（phase3 全局决选）",
    },
    # ── phase 3 · category 1:1（原 phase2 · 全局引擎决选对齐沙盒）──
    {
        "rule_id": "circuit_protection_icpdf_thermal_cutoff_cat_v1",
        "l3_id": "160103",
        "l3_cn": "热熔断体(温度保险丝)",
        "phase": 3,
        "rule_priority": 10,
        "clauses": [("category_eq", "热熔断路器/开关/保险丝", None, None)],
        "note": "overcurrent · thermal_cutoff（phase3 全局决选）",
    },
    {
        "rule_id": "circuit_protection_icpdf_tvs_cat_v1",
        "l3_id": "160201",
        "l3_cn": "TVS瞬态抑制二极管",
        "phase": 3,
        "rule_priority": 5,
        "clauses": [("category_eq", "TVS二极管", None, None)],
        "note": "semiconductor · tvs_diode（phase3 优先于 diode p2/p3）",
    },
    {
        "rule_id": "circuit_protection_icpdf_fuse_cat_v1",
        "l3_id": "160101",
        "l3_cn": "保险丝(熔断器)",
        "phase": 3,
        "rule_priority": 10,
        "clauses": [("category_eq", "保险丝", None, None)],
        "note": "overcurrent · fuse（phase3 优先于 resistor ptc）",
    },
    {
        "rule_id": "circuit_protection_icpdf_fuse_c2_v1",
        "l3_id": "160101",
        "l3_cn": "保险丝(熔断器)",
        "phase": 3,
        "rule_priority": 15,
        "clauses": [("category2_eq", "电熔丝", None, None)],
        "note": "tag 路径 · 电熔丝 → fuse（phase3 全局决选）",
    },
    {
        "rule_id": "circuit_protection_icpdf_telecom_c2_fallback_v1",
        "l3_id": "160203",
        "l3_cn": "晶闸管浪涌保护器(TSPD)",
        "phase": 3,
        "rule_priority": 7,
        "clauses": [("category2_eq", "电信保护电路", None, None)],
        "note": "电信叶 fallback · phase3 pri7 优先于 transistor p3 pri8",
    },
    {
        "rule_id": "circuit_protection_icpdf_mov_cat_v1",
        "l3_id": "160301",
        "l3_cn": "金属氧化物压敏电阻(MOV)",
        "phase": 3,
        "rule_priority": 8,
        "clauses": [("category_eq", "压敏电阻", None, None)],
        "note": "passive · mov · 学得捷精确 gate category",
    },
    {
        "rule_id": "circuit_protection_icpdf_mov_c2_v1",
        "l3_id": "160301",
        "l3_cn": "金属氧化物压敏电阻(MOV)",
        "phase": 3,
        "rule_priority": 10,
        "clauses": [("category2_eq", "压敏电阻", None, None)],
        "note": "passive · mov · category2=压敏电阻（不含非线性宽桶）",
    },
]
